// ==UserScript==
// @name         Cor De Fundo amarela
// @namespace    https://github.com/Androiderjs/Cor-de-fundo-KoGaMa
// @version      1.0
// @description  Muda a cor do fundo pra amarelo
// @author       Android DEV
// @match		 https://www.kogama.com/games/
// @match		 https://kogama.com.br/games/
// @match        https://friends.kogama.com/games/
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

alert ('Cor Selecionada: Amarela/Yellow')
document.body.style.background = 'Yellow'
