// ==UserScript==
// @name         Cor De Fundo Verde
// @namespace    https://github.com/Androiderjs/mudar-cor-de-fundo-KoGaMa-
// @version      1.0
// @description  Muda a cor do fundo pra verde
// @author       Android DEV
// @match		 https://www.kogama.com/games/
// @match		 https://kogama.com.br/games/
// @match        https://friends.kogama.com/games/
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

alert ('Cor Selecionada: Verde/Green')
document.body.style.background = 'green'
